--(c1)
ALTER TABLE FACT_TRANZACTII
ADD CONSTRAINT uni_tranzactii 
UNIQUE(ID_Client, ID_Cont, ID_Comerciant, ID_Canal_Plata, ID_Stare, ID_Locatie, ID_Data)
DISABLE VALIDATE;

--(c2)
ALTER TABLE DIM_CLIENT RENAME CONSTRAINT SYS_C007748 TO DIM_CLIENT_PK;
ALTER TABLE DIM_CLIENT MODIFY CONSTRAINT DIM_CLIENT_PK RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_client
FOREIGN KEY (ID_Client) 
REFERENCES DIM_CLIENT (ID_Client)
ENABLE NOVALIDATE;

--(c3)
ALTER TABLE DIM_DETALII_PLATA RENAME CONSTRAINT SYS_C007751 TO DIM_DETALII_PLATA_PK;
ALTER TABLE DIM_DETALII_PLATA MODIFY CONSTRAINT DIM_DETALII_PLATA_PK RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_detalii_plata
FOREIGN KEY (ID_Cont) 
REFERENCES DIM_DETALII_PLATA (ID_Cont)
ENABLE NOVALIDATE;

--(c4)
ALTER TABLE DIM_COMERCIANT RENAME CONSTRAINT SYS_C007752 TO DIM_COMERCIANT_PK;
ALTER TABLE DIM_COMERCIANT MODIFY CONSTRAINT DIM_COMERCIANT_PK RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_comerciant
FOREIGN KEY (ID_Comerciant) 
REFERENCES DIM_COMERCIANT (ID_Comerciant)
ENABLE NOVALIDATE;

--(c5)
ALTER TABLE DIM_CANAL_PLATA ADD CONSTRAINT DIM_CANAL_PLATA_PK PRIMARY KEY(ID_CANAL_PLATA) RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_canal_plata
FOREIGN KEY (ID_Canal_Plata) 
REFERENCES DIM_CANAL_PLATA (ID_Canal_Plata)
ENABLE NOVALIDATE;

--(c6)
ALTER TABLE DIM_STARE RENAME CONSTRAINT SYS_C007744 TO DIM_STARE_PK;
ALTER TABLE DIM_STARE MODIFY CONSTRAINT DIM_STARE_PK RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_stare
FOREIGN KEY (ID_Stare) 
REFERENCES DIM_STARE (ID_Stare)
ENABLE NOVALIDATE;

--(c7)
ALTER TABLE DIM_LOCATIE RENAME CONSTRAINT SYS_C007753 TO DIM_LOCATIE_PK;
ALTER TABLE DIM_LOCATIE MODIFY CONSTRAINT DIM_LOCATIE_PK RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_locatie
FOREIGN KEY (ID_Locatie) 
REFERENCES DIM_LOCATIE (ID_Locatie)
ENABLE NOVALIDATE;

--(c8)
ALTER TABLE DIM_CALENDAR ADD CONSTRAINT DIM_CALENDAR_PK PRIMARY KEY(ID_Data) RELY NOVALIDATE;

ALTER TABLE FACT_TRANZACTII ADD CONSTRAINT fk_data
FOREIGN KEY (ID_Data) 
REFERENCES DIM_CALENDAR (ID_Data)
RELY DISABLE NOVALIDATE;
