CREATE USER DW
    IDENTIFIED BY aSyifijdasfnlsjaJNSc;
GRANT CREATE SESSION TO DW;
GRANT CONNECT, DBA TO DW;

CREATE USER DB
    IDENTIFIED BY ufbivgfbdDHASU832fjdl;
GRANT CREATE SESSION TO DB;
GRANT CONNECT, DBA TO DB;
GRANT SELECT ON DB.TRANZACTII TO DW;
GRANT SELECT ON DB.CLIENTI TO DW;
GRANT SELECT ON DB.CARD TO DW;
GRANT SELECT ON DB.CONT TO DW;
GRANT SELECT ON DB.COMERCIANT TO DW;
GRANT SELECT ON DB.CANAL_PLATA TO DW;
GRANT SELECT ON DB.LOCATIE TO DW;